set fallback := true

default:
    @just --list

pull-provider dir:
    #!/usr/bin/env bash
    dir="{{dir}}"

    go run ./cmd/pull-provider/main.go "${dir}"

gen-provider dir: (pull-provider dir)
    #!/usr/bin/env bash
    dir="{{dir}}"

    mkdir -p "${dir}/gen"
    pushd template
    jb install
    jsonnet -S -J vendor --tla-code-file "provider=../${dir}/provider.json" main.libsonnet | jsonnetfmt - > "../${dir}/gen/main.libsonnet"
    popd

release-provider dir: (gen-provider dir)
    #!/usr/bin/env bash
    dir="{{dir}}"

    source="$(jsonnet -S -e "(import '${dir}/provider.json').source")"
    name="$(jsonnet -S -e "(import '${dir}/provider.json').name")"
    branch="terraform-provider/${source}"
    path="terraform-provider-${name}"
    gen="${dir}/gen"

    just jsonnet-release "${branch}" "${path}" "${gen}"
