set fallback := true

default:
    @just --list

release: test it
    @just jsonnet-release terraform

test:
    @jsonnet-kit test

it:
    #!/usr/bin/env bash
    echo "Running integration tests..."
    pushd it

    echo "Starting Docker Compose..."
    exit_code=0
    while read -r tst; do
      it="$(echo "${tst}" | jq -r '.[0]')"
      if [ "${it}" != "true" ]; then
        continue
      fi

      actual="$(echo "${tst}" | jq -r '.[1]')"
      mkdir -p tf
      touch tf/example.txt
      echo "${actual}" > tf/main.tf.json
      terraform -chdir=tf init
      terraform -chdir=tf plan
      rm -rf tf
    done < <(jsonnet '../main_tests.libsonnet' | jq -rc 'map([.it, .actual]) | .[]')

    if [ "${exit_code}" -eq 0 ]; then
      echo "All tests passed!"
    else
      echo "Some tests failed!"
    fi
    exit "${exit_code}"
